### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by BBQigniter** [boj/deckmaster-helldivers2#1]
thank, you so much for this!  it takes some time to get used to, but it's really awesome

but I found one issue  - the orbital laser-strike seems to be wrong 

see https://steamcommunity.com/sharedfiles/filedetails/?id=3161075951

i think it should be 

```
    laser-strike)
        #ctrl $RIGHT $DOWN $LEFT $UP $RIGHT $DOWN
        ctrl $RIGHT $DOWN $UP $RIGHT $DOWN
        ;;
```

**Comment by boj** [comment]
Thanks! Should be fixed.
