### ISSUE TITLE
Button presses are to fast

### ISSUE THREAD

**Issue by JRazman** [boj/deckmaster-helldivers2#2]
Is there a way to possibly add a delay between button presses?

I find the game doesn't register one or two sometime, and the stratagem doesn't get properly activated.

It mostly appears to be between ctrl and the next key press.

**Comment by boj** [comment]
@JRazman You could edit the delay in this line here: https://github.com/boj/deckmaster-helldivers2/blob/main/bin/helldivers#L15

I haven't been playing this game recently, but perhaps not having a delay after CTRL is the problem? By all means, experiment and report back your findings.

```bash
    # cmd="xdotool keydown $CTRL"
    cmd="xdotool key --delay 100 ctrl+l" # <-- try this
    for arg in $*; do
        cmd+=" key --delay 100 $arg"
    done
    cmd+=" keyup $CTRL"
```

From https://github.com/jordansissel/xdotool?tab=readme-ov-file#sending-keys

**Comment by JRazman** [comment]
Awesome!
That seems to be it. 100 was perfect last game I played with it set.

Thanks!
